#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'rubocop/daemon'

def cleanup
  `rm ~/.cache/rubocop-daemon/app/*`
end

Signal.trap('SIGTERM') { cleanup }

RuboCop::Daemon::CLI.new.run
